import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar
    home: 'Home',
    shop: 'Shop',
    our_story: 'Our Story',
    admin: 'Admin',
    portal: 'Portal',
    my_account: 'My Account',
    logout: 'Logout',
    sign_in: 'Sign In',
    cart: 'Cart',

    // Hero / landing
    hero_title: 'Pure Nature, Crafted in Laos',
    hero_desc: 'Experience the healing touch of botanicals from Luang Prabang. Hand-made skincare for your daily ritual.',
    hero_button: 'Shop the Collection',
    popular_title: 'Popular Favorites',
    popular_subtitle: 'The most loved natural skincare rituals in Laos.',
    view_all: 'View All',
    story_title: 'Our Story',
    story_subtitle: 'Since 2011, Lao Natural has been guided by three core missions:',
    
    // Missions
    mission1_title: 'Providing Truly Lao Products',
    mission1_desc: 'We create authentic Lao products using locally sourced materials, ensuring they support local communities and offer a genuine Lao experience.',
    mission2_title: 'Supporting Ethnic Minorities',
    mission2_desc: 'We empower ethnic minorities by providing employment opportunities and educational support, helping improve lives and foster community growth.',
    mission3_title: 'Promoting Environmental Responsibility',
    mission3_desc: 'We prioritize sustainability through eco-friendly packaging, waste reduction, and responsible sourcing, aiming to minimize our environmental footprint.',

    // Ingredients
    ingredients_title: "What It's Made From",
    ingredients_subtitle: 'Only the purest botanicals to nourish your skin and soul.',
    ing_frangipani: 'Frangipani',
    ing_honey: 'Wild Honey',
    ing_lemongrass: 'Lemongrass',
    ing_coconut: 'Coconut',
    ing_rice: 'Rice',
    ing_coffee: 'Coffee',
    ing_peppermint: 'Peppermint',
    ing_turmeric: 'Turmeric',

    // Footer
    footer_desc: 'Handcrafted natural skincare and wellness products from Luang Prabang, bringing the healing touch of nature to your daily routine.',
    quick_links: 'Quick Links',
    contact: 'Contact',
    scan_qr: 'Scan QR',
    scan_desc: 'Scan to view our official page or complete payment transfers.',
    rights_reserved: 'Lao Natural Essentials. All rights reserved.',

    // Products page
    products_title: 'Products',
    products_subtitle: 'Organic skincare and hand-made remedies from Luang Prabang.',
    all_categories: 'All Categories',
    search_placeholder: 'Search products...',
    sort_by: 'Sort by',
    sort_featured: 'Featured',
    sort_low_high: 'Price: Low to High',
    sort_high_low: 'Price: High to Low',
    sort_in_stock: 'In Stock',
    view_details: 'View Details',

    // Product Detail page
    back_products: 'Back to Products',
    select_size: 'Select Size',
    quantity: 'Quantity',
    add_to_cart: 'Add to Cart',
    out_of_stock: 'Out of Stock',
    ingredients_tab: 'Ingredients',
    description_tab: 'Description',
    size_price: 'Size & Price',

    // Cart page
    cart_title: 'Your Cart',
    cart_empty: 'Your cart is empty.',
    continue_shopping: 'Continue Shopping',
    item: 'Item',
    price: 'Price',
    qty: 'Qty',
    total: 'Total',
    subtotal: 'Subtotal',
    proceed_checkout: 'Proceed to Checkout',

    // Checkout page
    checkout_title: 'Checkout',
    contact_info: 'Contact Information',
    shipping_details: 'Shipping Details',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    country: 'Country',
    province: 'Province',
    delivery_address: 'Delivery Address',
    express_company: 'Express Shipping Company',
    express_placeholder: 'E.g., HAL Express, Anousith, etc.',
    order_summary: 'Order Summary',
    place_order: 'Place Order & Pay',
    shipping_cost: 'Shipping Cost',
    coupon_code: 'Coupon Code',
    apply: 'Apply',

    // Order Detail page
    order_tracking: 'Order Tracking',
    status: 'Status',
    tracking_number: 'Tracking Number',
    delivery_info: 'Delivery Information',
    submit_proof: 'Submit Payment Proof',
    proof_desc: 'Upload BCEL One QR Transfer Slip to complete your order.',
    choose_file: 'Choose File',
    upload_slip: 'Upload Slip',
    status_pending: 'Awaiting Payment Verification',
    status_prepare: 'Preparing Order',
    status_sending: 'Shipped & In Transit',
    status_received: 'Received & Completed',

    // Dashboard
    profile_details: 'Profile Details',
    order_history: 'Order History',
    no_orders: 'You have not placed any orders yet.',

    // Login
    email_address: 'Email Address',
    dont_have_account: "Don't have an account? Sign up here.",

    // Portal additions
    "Dashboard": "Dashboard",
    "Total Revenue": "Total Revenue",
    "Import Revenue": "Import Revenue",
    "Sell History": "Sell History",
    "Reports & Invoices": "Reports & Invoices",
    "Import Products": "Import Products",
    "Product Catalog": "Product Catalog",
    "Category Management": "Category Management",
    "All Users": "All Users",
    "Employees": "Employees",
    "Customers": "Customers",
    "View Store": "View Store",
    "Sign Out": "Sign Out",
    "Hero Banners": "Hero Banners",
    "Products": "Products",
    "Categories": "Categories",
    "Orders": "Orders",
    "Add products to the store catalog": "Add products to the store catalog",
    "Import Product": "Import Product",
    "Total Products": "Total Products",
    "Low Stock": "Low Stock",
    "Out of Stock": "Out of Stock",
    "Product": "Product",
    "Category": "Category",
    "Price": "Price",
    "Stock": "Stock",
    "Actions": "Actions",
    "No products imported yet": "No products imported yet",
    "Edit Product": "Edit Product",
    "Import New Product": "Import New Product",
    "Product Image": "Product Image",
    "Product Name *": "Product Name *",
    "Supplier Name (Optional)": "Supplier Name (Optional)",
    "Import Date": "Import Date",
    "Import Price (₭) *": "Import Price (₭) *",
    "Sell Price (₭) *": "Sell Price (₭) *",
    "Stock *": "Stock *",
    "Import History": "Import History",
    "Supplier": "Supplier",
    "Import Price": "Import Price",
    "Imported Qty": "Imported Qty",
    "No imports recorded for this product": "No imports recorded for this product",
    "Detailed inventory and product information": "Detailed inventory and product information",
    "Search by name, ID, or category...": "Search by name, ID, or category...",
    "Loading botanicals...": "Loading botanicals...",
    "units": "units",
    "No products found in the catalog": "No products found in the catalog",
    "Uncategorized": "Uncategorized",
    "Sell Price": "Sell Price",
    "In Stock": "In Stock",
    "Imported By": "Imported By",
    "Verified": "Verified",
    "No description available for this botanical product.": "No description available for this botanical product.",
    "Ingredients not specified.": "Ingredients not specified.",
    "Unit Size": "Unit Size",
    "Close Catalog": "Close Catalog",
    "Manage product categories for the store": "Manage product categories for the store",
    "Search categories...": "Search categories...",
    "No categories found.": "No categories found.",
    "New Category": "New Category",
    "Edit Category": "Edit Category",
    "Save Category": "Save Category",
    "Category Name": "Category Name",
    "View and manage all customer transactions": "View and manage all customer transactions",
    "Search orders...": "Search orders...",
    "Fetching records...": "Fetching records...",
    "Order ID": "Order ID",
    "Customer": "Customer",
    "Date & Time": "Date & Time",
    "Total Amount": "Total Amount",
    "No orders found matching your search.": "No orders found matching your search.",
    "Order Details": "Order Details",
    "Order Summary": "Order Summary",
    "Subtotal": "Subtotal",
    "Payment Slip": "Payment Slip",
    "Shipping Address": "Shipping Address",
    "No screenshot slip uploaded yet.": "No screenshot slip uploaded yet.",
    "Verify Payment & Prepare Order": "Verify Payment & Prepare Order",
    "Ship Order (Add Tracking Number)": "Ship Order (Add Tracking Number)",
    "Complete / Set Received": "Complete / Set Received",
    "Mark Order as Received": "Mark Order as Received",
    "Close Details": "Close Details",
    "Generate and print authentic Lao Natural Sole Co. invoices and track transactions": "Generate and print authentic Lao Natural Sole Co. invoices and track transactions",
    "All Time": "All Time",
    "Today": "Today",
    "Past 7 Days": "Past 7 Days",
    "Past 30 Days": "Past 30 Days",
    "Search invoices...": "Search invoices...",
    "Total Sales": "Total Sales",
    "Total Revenue (LAK)": "Total Revenue (LAK)",
    "Shipping Collected": "Shipping Collected",
    "Items Sold": "Items Sold",
    "Invoices List": "Invoices List",
    "Total": "Total",
    "Print Invoice": "Print Invoice",
    "Lao Natural Sole Co., Ltd": "Lao Natural Sole Co., Ltd",
    "Ban Mano, Luang Prabang, Laos": "Ban Mano, Luang Prabang, Laos",
    "INVOICE": "INVOICE",
    "Invoice To:": "Invoice To:",
    "Invoice Details:": "Invoice Details:",
    "Invoice No:": "Invoice No:",
    "Date:": "Date:",
    "Payment Method:": "Payment Method:",
    "BCEL One Transfer": "BCEL One Transfer",
    "Item Description": "Item Description",
    "Qty": "Qty",
    "Unit Price": "Unit Price",
    "Amount": "Amount",
    "VAT (10%)": "VAT (10%)",
    "Shipping Cost": "Shipping Cost",
    "Grand Total": "Grand Total",
    "Thank you for your business!": "Thank you for your business!",
    "Authorized Signature": "Authorized Signature",
    "Manage store employees": "Manage store employees",
    "View registered customers": "View registered customers",
    "All employees & customers": "All employees & customers",
    "Search users...": "Search users...",
    "Add Employee": "Add Employee",
    "Add Customer": "Add Customer",
    "Add User": "Add User",
    "User Details": "User Details",
    "Joined": "Joined",
    "No phone": "No phone",
    "No users found": "No users found",
    "Add New User": "Add New User",
    "Edit User": "Edit User",
    "Profile Picture (Optional)": "Profile Picture (Optional)",
    "Full Name *": "Full Name *",
    "Email *": "Email *",
    "Password *": "Password *",
    "Password (leave blank to keep)": "Password (leave blank to keep)",
    "Phone": "Phone",
    "Address": "Address",
    "Create User": "Create User",
    "Save Changes": "Save Changes",
    "User Profile": "User Profile",
    "Email Address": "Email Address",
    "Contact Number": "Contact Number",
    "Physical Address": "Physical Address",
    "Not provided": "Not provided",
    "No address registered": "No address registered",
    "Express": "Express",
    "Close Profile": "Close Profile",
    "Add details to owner-imported product listings": "Add details to owner-imported product listings",
    "No products found": "No products found",
    "Upload and manage active background banners on the landing page slider.": "Upload and manage active background banners on the landing page slider.",
    "Upload New Banner": "Upload New Banner",
    "Slideshow Settings": "Slideshow Settings",
    "Set the transition speed of the background image carousel in seconds.": "Set the transition speed of the background image carousel in seconds.",
    "Slide Interval:": "Slide Interval:",
    "1 Second": "1 Second",
    "2 Seconds": "2 Seconds",
    "3 Seconds": "3 Seconds",
    "4 Seconds": "4 Seconds",
    "5 Seconds": "5 Seconds",
    "6 Seconds": "6 Seconds",
    "8 Seconds": "8 Seconds",
    "10 Seconds": "10 Seconds",
    "Loading banners...": "Loading banners...",
    "No Custom Banners": "No Custom Banners",
    "Create a beautiful homepage! Upload custom high-resolution banner photos to display in the main slideshow rotation.": "Create a beautiful homepage! Upload custom high-resolution banner photos to display in the main slideshow rotation.",
    "Upload First Banner": "Upload First Banner",
    "Delete": "Delete",
    "Orders & Shipping": "Orders & Shipping",
    "Manage order statuses and shipping": "Manage order statuses and shipping",
    "Order #": "Order #",
    "Date": "Date",
    "Update Status": "Update Status",
    "All": "All",
    "Pending": "Pending",
    "Preparing": "Preparing",
    "Shipping": "Shipping",
    "Received": "Received",
    "Pending Payment": "Pending Payment",
    "Prepare": "Prepare",
    "Sending": "Sending",
    "No orders found": "No orders found",
    "Total Revenue Report": "Total Revenue Report",
    "Detailed breakdown of sales income and orders": "Detailed breakdown of sales income and orders",
    "Import Revenue Report": "Import Revenue Report",
    "Detailed breakdown of product import costs": "Detailed breakdown of product import costs",
    "Total Earned": "Total Earned",
    "Exclude pending": "Exclude pending",
    "Orders Completed": "Orders Completed",
    "Paid/received items": "Paid/received items",
    "Avg Order Value": "Avg Order Value",
    "Per paid transaction": "Per paid transaction",
    "Pending Income": "Pending Income",
    "orders awaiting proof": "orders awaiting proof",
    "Analyzing sales history...": "Analyzing sales history...",
    "Customer Info": "Customer Info",
    "Date Issued": "Date Issued",
    "Revenue Amount": "Revenue Amount",
    "No matching sales or orders found.": "No matching sales or orders found.",
    "Order Breakdown": "Order Breakdown",
    "Customer Details": "Customer Details",
    "Recipient Name": "Recipient Name",
    "Order Date": "Order Date",
    "Order Time": "Order Time",
    "Total Paid": "Total Paid",
    "BCEL One QR Receipt": "BCEL One QR Receipt",
    "Open Slip": "Open Slip",
    "Verify & Approve": "Verify & Approve",
    "Purchased Items": "Purchased Items",
    "All Statuses": "All Statuses",
    "Awaiting Payment": "Awaiting Payment",
    "Procurement Spent": "Procurement Spent",
    "Total import cost value": "Total import cost value",
    "Total Qty Imported": "Total Qty Imported",
    "Total items in stock intake": "Total items in stock intake",
    "Avg Procurement Cost": "Avg Procurement Cost",
    "Per import batch ticket": "Per import batch ticket",
    "Unique Items": "Unique Items",
    "Distinct products stocked": "Distinct products stocked",
    "Fetching import records...": "Fetching import records...",
    "Import ID": "Import ID",
    "Product Details": "Product Details",
    "Quantity": "Quantity",
    "Unit Cost": "Unit Cost",
    "Total Expense": "Total Expense",
    "No matching import records found.": "No matching import records found.",
    "Search product or supplier...": "Search product or supplier...",
    "Save Details": "Save Details",
    "Cancel": "Cancel",
    "Saving...": "Saving...",
    "Description": "Description",
    "Ingredients": "Ingredients",
    "Welcome back, ": "Welcome back, ",
    ". Here's your store overview.": ". Here's your store overview.",
    "Total Orders": "Total Orders",
    "Recent Orders": "Recent Orders",
    "View All": "View All",
    "Order": "Order",
    "No orders yet": "No orders yet",
    "All stocked up ✓": "All stocked up ✓",
    "Top Selling Products": "Top Selling Products",
    "No sales yet": "No sales yet",
    "Quick Actions": "Quick Actions",
    "Manage Users": "Manage Users",
    "Employee Portal": "Employee Portal",
    "Loading analytics": "Loading analytics",
    "Employee Dashboard": "Employee Dashboard",
    "Welcome, ": "Welcome, ",
    ". Here's today's overview.": ". Here's today's overview.",
    "Pending Orders": "Pending Orders",
    "New Orders": "New Orders",
    "New": "New",
    "Employee Sales Log": "Employee Sales Log",
    "Orders Sold": "Orders Sold",
    "No employee sales records found": "No employee sales records found",
    "No orders sold yet": "No orders sold yet",
    "Shipped Today": "Shipped Today",
    "No recent orders": "No recent orders",
    "Manage Products": "Manage Products",
    "Manage Orders & Shipping": "Manage Orders & Shipping",
    "View Storefront": "View Storefront",
    "Orders by Status": "Orders by Status",
    "Loading dashboard": "Loading dashboard"
  },
  la: {
    // Navbar
    home: 'ໜ້າຫຼັກ',
    shop: 'ຮ້ານຄ້າ',
    our_story: 'ຄວາມເປັນມາ',
    admin: 'ຜູ້ດູແລ',
    portal: 'ປະຕູພະນັກງານ',
    my_account: 'ບັນຊີຂອງຂ້ອຍ',
    logout: 'ອອກຈາກລະບົບ',
    sign_in: 'ເຂົ້າສູ່ລະບົບ',
    cart: 'ກະຕ່າ',

    // Hero / landing
    hero_title: 'ທຳມະຊາດແທ້, ຜະລິດໃນລາວ',
    hero_desc: 'ສຳພັດກັບການບຳລຸງຈາກທຳມະຊາດຂອງຫຼວງພຣະບາງ. ຜະລິດຕະພັນບຳລຸງຜິວທີ່ເຮັດດ້ວຍມືສຳລັບຊີວິດປະຈຳວັນຂອງທ່ານ.',
    hero_button: 'ເລືອກຊື້ຜະລິດຕະພັນ',
    popular_title: 'ຜະລິດຕະພັນຍອດນິຍົມ',
    popular_subtitle: 'ຜະລິດຕະພັນບຳລຸງຜິວຈາກທຳມະຊາດທີ່ໄດ້ຮັບຄວາມນິຍົມທີ່ສຸດໃນປະເທດລາວ.',
    view_all: 'ເບິ່ງທັງໝົດ',
    story_title: 'ຄວາມເປັນມາຂອງພວກເຮົາ',
    story_subtitle: 'ຕັ້ງແຕ່ປີ 2011, ລາວເນເຊີໂຣ (Lao Natural) ໄດ້ດຳເນີນງານພາຍໃຕ້ 3 ພັນທະກິດຫຼັກ:',
    
    // Missions
    mission1_title: 'ສະໜອງຜະລິດຕະພັນລາວຢ່າງແທ້ຈິງ',
    mission1_desc: 'ພວກເຮົາສ້າງສັນຜະລິດຕະພັນລາວທີ່ແທ້ຈິງໂດຍນຳໃຊ້ວັດຖຸດິບພາຍໃນທ້ອງຖິ່ນ, ເພື່ອສະໜັບສະໜູນຊຸມຊົນທ້ອງຖິ່ນ ແລະ ມອບປະສົບການລາວຢ່າງແທ້ຈິງ.',
    mission2_title: 'ສະໜັບສະໜູນກຸ່ມຊົນເຜົ່າສ່ວນໜ້ອຍ',
    mission2_desc: 'ພວກເຮົາສົ່ງເສີມກຸ່ມຊົນເຜົ່າສ່ວນໜ້ອຍໂດຍການສ້າງໂອກາດໃນການເຮັດວຽກ ແລະ ສະໜັບສະໜູນດ້ານການສຶກສາ, ເພື່ອຊ່ວຍພັດທະນາຄຸນນະພາບຊີວິດ ແລະ ການເຕີບໂຕຂອງຊຸມຊົນ.',
    mission3_title: 'ສົ່ງເສີມຄວາມຮັບຜິດຊອບຕໍ່ສິ່ງແວດລ້ອມ',
    mission3_desc: 'ພວກເຮົາໃຫ້ຄວາມສຳຄັນກັບຄວາມຍືນຍົງ ໂດຍການນຳໃຊ້ບັນຈຸພັນທີ່ເປັນມິດຕໍ່ສິ່ງແວດລ້ອມ, ຫຼຸດຜ່ອນຂີ້ເຫຍື້ອ ແລະ ການຈັດຫາວັດຖຸດິບຢ່າງມີຄວາມຮັບຜິດຊອບ, ເພື່ອຫຼຸດຜ່ອນຜົນກະທົບຕໍ່ສິ່ງແວດລ້ອມ.',

    // Ingredients
    ingredients_title: "ສ່ວນປະກອບຫຼັກຂອງພວກເຮົາ",
    ingredients_subtitle: 'ສະໝຸນໄພ ແລະ ພືດພັນທຳມະຊາດທີ່ບໍລິສຸດທີ່ສຸດເພື່ອບຳລຸງຜິວ ແລະ ຈິດວິນຍານຂອງທ່ານ.',
    ing_frangipani: 'ດອກຈຳປາ',
    ing_honey: 'ນ້ຳເຜິ້ງປ່າ',
    ing_lemongrass: 'ຫົວສິງໄຄ',
    ing_coconut: 'ໝາກພ້າວ',
    ing_rice: 'ເຂົ້າ',
    ing_coffee: 'ກາເຟ',
    ing_peppermint: 'ສະລະແໜ່',
    ing_turmeric: 'ຂີ້ໝິ້ນ',

    // Footer
    footer_desc: 'ຜະລິດຕະພັນບຳລຸງຜິວ ແລະ ສຸຂະພາບຈາກທຳມະຊາດ ທີ່ຜະລິດດ້ວຍມືຈາກຫຼວງພຣະບາງ, ມອບການບຳລຸງຈາກທຳມະຊາດໃຫ້ກັບຊີວິດປະຈຳວັນຂອງທ່ານ.',
    quick_links: 'ລິ້ງຄ໌ດ່ວນ',
    contact: 'ຕິດຕໍ່ພວກເຮົາ',
    scan_qr: 'ສະແກນ QR',
    scan_desc: 'ສະແກນເພື່ອເບິ່ງໜ້າທາງການຂອງພວກເຮົາ ຫຼື ເຮັດທຸລະກຳການຊຳລະເງິນ.',
    rights_reserved: 'ລາວເນເຊີໂຣ ເອສເຊັນໂຊ. ສິດທິທັງໝົດຖືກສະຫງວນ.',

    // Products page
    products_title: 'ຜະລິດຕະພັນທັງໝົດ',
    products_subtitle: 'ຜະລິດຕະພັນບຳລຸງຜິວອໍແກນິກ ແລະ ຜະລິດຕະພັນທີ່ເຮັດດ້ວຍມືຈາກຫຼວງພຣະບາງ.',
    all_categories: 'ໝວດໝູ່ທັງໝົດ',
    search_placeholder: 'ຄົ້ນຫາຜະລິດຕະພັນ...',
    sort_by: 'ຈັດລຽງໂດຍ',
    sort_featured: 'ແນະນຳ',
    sort_low_high: 'ລາຄາ: ແຕ່ຕ່ຳຫາສູງ',
    sort_high_low: 'ລາຄາ: ແຕ່ສູງຫາຕ່ຳ',
    sort_in_stock: 'ມີໃນສາງ',
    view_details: 'ເບິ່ງລາຍລະອຽດ',

    // Product Detail page
    back_products: 'ກັບຄືນໜ້າຜະລິດຕະພັນ',
    select_size: 'ເລືອກຂະໜາດ',
    quantity: 'ຈຳນວນ',
    add_to_cart: 'ເພີ່ມເຂົ້າກະຕ່າ',
    out_of_stock: 'ໝົດສາງ',
    ingredients_tab: 'ສ່ວນປະກອບ',
    description_tab: 'ລາຍລະອຽດ',
    size_price: 'ຂະໜາດ ແລະ ລາຄາ',

    // Cart page
    cart_title: 'ກະຕ່າຂອງທ່ານ',
    cart_empty: 'ກະຕ່າຂອງທ່ານວ່າງເປົ່າ.',
    continue_shopping: 'ເລືອກຊື້ສິນຄ້າຕໍ່',
    item: 'ສິນຄ້າ',
    price: 'ລາຄາ',
    qty: 'ຈຳນວນ',
    total: 'ລວມ',
    subtotal: 'ລາຄາລວມ',
    proceed_checkout: 'ດຳເນີນການຊຳລະເງິນ',

    // Checkout page
    checkout_title: 'ຊຳລະເງິນ',
    contact_info: 'ຂໍ້ມູນການຕິດຕໍ່',
    shipping_details: 'ລາຍລະອຽດການຈັດສົ່ງ',
    full_name: 'ຊື່ ແລະ ນາມສະກຸນ',
    phone_number: 'ເບີໂທລະສັບ',
    country: 'ປະເທດ',
    province: 'ແຂວງ',
    delivery_address: 'ທີ່ຢູ່ຈັດສົ່ງ',
    express_company: 'ບໍລິສັດຂົນສົ່ງ',
    express_placeholder: 'ຕົວຢ່າງ: HAL Express, Anousith Express, ແລະອື່ນໆ.',
    order_summary: 'ສະຫຼຸບການສັ່ງຊື້',
    place_order: 'ຢືນຢັນການສັ່ງຊື້ ແລະ ຊຳລະເງິນ',
    shipping_cost: 'ຄ່າຈັດສົ່ງ',
    coupon_code: 'ລະຫັດຄູປອງ',
    apply: 'ນຳໃຊ້',

    // Order Detail page
    order_tracking: 'ຕິດຕາມການສັ່ງຊື້',
    status: 'ສະຖານະ',
    tracking_number: 'ເລກຕິດຕາມພັດສະດຸ',
    delivery_info: 'ຂໍ້ມູນການຈັດສົ່ງ',
    submit_proof: 'ສົ່ງຫຼັກຖານການຊຳລະເງິນ',
    proof_desc: 'ອັບໂຫຼດສະລິບການໂອນເງິນ BCEL One ເພື່ອຢືນຢັນການສັ່ງຊື້.',
    choose_file: 'ເລືອກຮູບພາບ',
    upload_slip: 'ອັບໂຫຼດສະລິບ',
    status_pending: 'ກຳລັງກວດສອບການຊຳລະເງິນ',
    status_prepare: 'ກຳລັງກຽມຈັດສົ່ງ',
    status_sending: 'ຈັດສົ່ງແລ້ວ',
    status_received: 'ໄດ້ຮັບສິນຄ້າແລ້ວ',

    // Dashboard
    profile_details: 'ລາຍລະອຽດໂປຣໄຟລ໌',
    order_history: 'ປະຫວັດການສັ່ງຊື້',
    no_orders: 'ທ່ານຍັງບໍ່ທັນມີລາຍການສັ່ງຊື້ເທື່ອ.',

    // Login
    email_address: 'ທີ່ຢູ່ອີເມວ',
    dont_have_account: 'ຍັງບໍ່ທັນມີບັນຊີບໍ? ສະໝັກສະມາຊິກຢູ່ນີ້.',

    // Portal additions
    "Dashboard": "ກະດານຄວບຄຸມ",
    "Total Revenue": "ລາຍຮັບທັງໝົດ",
    "Import Revenue": "ຕົ້ນທຶນນຳເຂົ້າ",
    "Sell History": "ປະຫວັດການຂາຍ",
    "Reports & Invoices": "ລາຍງານ & ໃບບິນ",
    "Import Products": "ນຳເຂົ້າສິນຄ້າ",
    "Product Catalog": "ລາຍການສິນຄ້າ",
    "Category Management": "ຈັດການໝວດໝູ່",
    "All Users": "ຜູ້ໃຊ້ທັງໝົດ",
    "Employees": "ພະນັກງານ",
    "Customers": "ລູກຄ້າ",
    "View Store": "ເບິ່ງໜ້າຮ້ານ",
    "Sign Out": "ອອກຈາກລະບົບ",
    "Hero Banners": "ແບນເນີໂຄສະນາ",
    "Products": "ສິນຄ້າ",
    "Categories": "ໝວດໝູ່",
    "Orders": "ລາຍການສັ່ງຊື້",
    "Add products to the store catalog": "ເພີ່ມລາຍລະອຽດໃຫ້ກັບລາຍການສິນຄ້າທີ່ນຳເຂົ້າໂດຍເຈົ້າຂອງ",
    "Import Product": "ນຳເຂົ້າສິນຄ້າ",
    "Total Products": "ສິນຄ້າທັງໝົດ",
    "Low Stock": "ສິນຄ້າໃກ້ໝົດ",
    "Out of Stock": "ສິນຄ້າໝົດ",
    "Product": "ສິນຄ້າ",
    "Category": "ໝວດໝູ່",
    "Price": "ລາຄາ",
    "Stock": "ຄັງສິນຄ້າ",
    "Actions": "ການດຳເນີນການ",
    "No products imported yet": "ຍັງບໍ່ມີສິນຄ້ານຳເຂົ້າ",
    "Edit Product": "ແກ້ໄຂສິນຄ້າ",
    "Import New Product": "ນຳເຂົ້າສິນຄ້າໃໝ່",
    "Product Image": "ຮູບພາບສິນຄ້າ",
    "Product Name *": "ຊື່ສິນຄ້າ *",
    "Supplier Name (Optional)": "ຊື່ຜູ້ສະໜອງ (ຖ້າມີ)",
    "Import Date": "ວັນທີນຳເຂົ້າ",
    "Import Price (₭) *": "ລາຄານຳເຂົ້າ (₭) *",
    "Sell Price (₭) *": "ລາຄາຂາຍ (₭) *",
    "Stock *": "ຄັງສິນຄ້າ *",
    "Import History": "ປະຫວັດການນຳເຂົ້າ",
    "Supplier": "ຜູ້ສະໜອງ",
    "Import Price": "ລາຄານຳເຂົ້າ",
    "Imported Qty": "ຈຳນວນນຳເຂົ້າ",
    "No imports recorded for this product": "ບໍ່ມີບັນທຶກການນຳເຂົ້າສຳລັບສິນຄ້ານີ້",
    "Detailed inventory and product information": "ຂໍ້ມູນສິນຄ້າ ແລະ ຄັງສິນຄ້າແບບລະອຽດ",
    "Search by name, ID, or category...": "ຄົ້ນຫາດ້ວຍຊື່, ລະຫັດ ຫຼື ໝວດໝູ່...",
    "Loading botanicals...": "ກຳລັງໂຫລດຂໍ້ມູນສະໝຸນໄພ...",
    "units": "ຊິ້ນ",
    "No products found in the catalog": "ບໍ່ພົບສິນຄ້າໃນລາຍການ",
    "Uncategorized": "ບໍ່ມີໝວດໝູ່",
    "Sell Price": "ລາຄາຂາຍ",
    "In Stock": "ມີໃນຄັງ",
    "Imported By": "ນຳເຂົ້າໂດຍ",
    "Verified": "ຢືນຢັນແລ້ວ",
    "No description available for this botanical product.": "ບໍ່ມີລາຍລະອຽດສຳລັບສິນຄ້ານີ້.",
    "Ingredients not specified.": "ບໍ່ໄດ້ລະບຸສ່ວນປະກອບ.",
    "Unit Size": "ຂະໜາດບັນຈຸ",
    "Close Catalog": "ປິດລາຍການ",
    "Manage product categories for the store": "ຈັດການໝວດໝູ່ສິນຄ້າສຳລັບຮ້ານຄ້າ",
    "Search categories...": "ຄົ້ນຫາໝວດໝູ່...",
    "No categories found.": "ບໍ່ພົບໝວດໝູ່.",
    "New Category": "ໝວດໝູ່ໃໝ່",
    "Edit Category": "ແກ້ໄຂໝວດໝູ່",
    "Save Category": "ບັນທຶກໝວດໝູ່",
    "Category Name": "ຊື່ໝວດໝູ່",
    "View and manage all customer transactions": "ເບິ່ງ ແລະ ຈັດການທຸລະກຳຂອງລູກຄ້າທັງໝົດ",
    "Search orders...": "ຄົ້ນຫາລາຍການສັ່ງຊື້...",
    "Fetching records...": "ກຳລັງດຶງຂໍ້ມູນ...",
    "Order ID": "ລະຫັດໃບບິນ",
    "Customer": "ລູກຄ້າ",
    "Date & Time": "ວັນທີ & ເວລາ",
    "Total Amount": "ຍອດລວມທັງໝົດ",
    "No orders found matching your search.": "ບໍ່ພົບລາຍການສັ່ງຊື້ທີ່ຄົ້ນຫາ.",
    "Order Details": "ລາຍລະອຽດໃບບິນ",
    "Order Summary": "ສະຫຼຸບລາຍການສັ່ງຊື້",
    "Subtotal": "ຍອດລວມ",
    "Payment Slip": "ສະລິບການຈ່າຍເງິນ",
    "Shipping Address": "ທີ່ຢູ່ຈັດສົ່ງ",
    "No screenshot slip uploaded yet.": "ຍັງບໍ່ທັນມີການອັບໂຫລດສະລິບ.",
    "Verify Payment & Prepare Order": "ຢືນຢັນການຊຳລະເງິນ & ຕຽມສິນຄ້າ",
    "Ship Order (Add Tracking Number)": "ຈັດສົ່ງສິນຄ້າ (ເພີ່ມເລກຕິດຕາມ)",
    "Complete / Set Received": "ສຳເລັດ / ຕັ້ງຄ່າເປັນໄດ້ຮັບແລ້ວ",
    "Mark Order as Received": "ໝາຍວ່າໄດ້ຮັບສິນຄ້າແລ້ວ",
    "Close Details": "ປິດລາຍລະອຽດ",
    "Generate and print authentic Lao Natural Sole Co. invoices and track transactions": "ສ້າງ ແລະ ພິມໃບບິນບໍລິສັດ ລາວ ເນເຊີຣັລ ແລະ ຕິດຕາມທຸລະກຳ",
    "All Time": "ທັງໝົດ",
    "Today": "ມື້ນີ້",
    "Past 7 Days": "7 ວັນຜ່ານມາ",
    "Past 30 Days": "30 ວັນຜ່ານມາ",
    "Search invoices...": "ຄົ້ນຫາໃບບິນ...",
    "Total Sales": "ຍອດຂາຍທັງໝົດ",
    "Total Revenue (LAK)": "ລາຍຮັບທັງໝົດ (ກີບ)",
    "Shipping Collected": "ຄ່າຈັດສົ່ງທີ່ເກັບໄດ້",
    "Items Sold": "ຈຳນວນສິນຄ້າທີ່ຂາຍໄດ້",
    "Invoices List": "ລາຍການໃບບິນ",
    "Total": "ຍອດລວມ",
    "Print Invoice": "ພິມໃບບິນ",
    "Lao Natural Sole Co., Ltd": "ບໍລິສັດ ລາວ ເນເຊີຣັລ ຈຳກັດ",
    "Ban Mano, Luang Prabang, Laos": "ບ້ານ ມະໂນ, ຫຼວງພະບາງ, ລາວ",
    "INVOICE": "INVOICE",
    "Invoice To:": "ສົ່ງເຖິງ:",
    "Invoice Details:": "ລາຍລະອຽດໃບບິນ:",
    "Invoice No:": "ເລກທີໃບບິນ:",
    "Date:": "ວັນທີ:",
    "Payment Method:": "ວິທີການຊຳລະ:",
    "BCEL One Transfer": "ໂອນຜ່ານ BCEL One",
    "Item Description": "ລາຍການສິນຄ້າ",
    "Qty": "ຈຳນວນ",
    "Unit Price": "ລາຄາຕໍ່ໜ່ວຍ",
    "Amount": "ມູນຄ່າ",
    "VAT (10%)": "ອາກອນມູນຄ່າເພີ່ມ (10%)",
    "Shipping Cost": "ຄ່າຈັດສົ່ງ",
    "Grand Total": "ຍອດລວມສຸດທິ",
    "Thank you for your business!": "ຂໍຂອບໃຈທີ່ໃຊ້ບໍລິການ!",
    "Authorized Signature": "ລາຍເຊັນຜູ້ມີອຳນາດ",
    "Manage store employees": "ຈັດການພະນັກງານຮ້ານ",
    "View registered customers": "ເບິ່ງລູກຄ້າທີ່ລົງທະບຽນ",
    "All employees & customers": "ພະນັກງານ & ລູກຄ້າທັງໝົດ",
    "Search users...": "ຄົ້ນຫາຜູ້ໃຊ້...",
    "Add Employee": "ເພີ່ມພະນັກງານ",
    "Add Customer": "ເພີ່ມລູກຄ້າ",
    "Add User": "ເພີ່ມຜູ້ໃຊ້",
    "User Details": "ລາຍລະອຽດຜູ້ໃຊ້",
    "Joined": "ເຂົ້າຮ່ວມເມື່ອ",
    "No phone": "ບໍ່ມີເບີໂທ",
    "No users found": "ບໍ່ພົບຜູ້ໃຊ້",
    "Add New User": "ເພີ່ມຜູ້ໃຊ້ໃໝ່",
    "Edit User": "ແກ້ໄຂຜູ້ໃຊ້",
    "Profile Picture (Optional)": "ຮູບໂປຣໄຟລ໌ (ຖ້າມີ)",
    "Full Name *": "ຊື່ເຕັມ *",
    "Email *": "ອີເມວ *",
    "Password *": "ລະຫັດຜ່ານ *",
    "Password (leave blank to keep)": "ລະຫັດຜ່ານ (ປະຫວ່າງໄວ້ຖ້າບໍ່ຕ້ອງການປ່ຽນ)",
    "Phone": "ເບີໂທລະສັບ",
    "Address": "ທີ່ຢູ່",
    "Create User": "ສ້າງຜູ້ໃຊ້",
    "Save Changes": "ບັນທຶກການປ່ຽນແປງ",
    "User Profile": "ໂປຣໄຟລ໌ຜູ້ໃຊ້",
    "Email Address": "ທີ່ຢູ່ອີເມວ",
    "Contact Number": "ເບີໂທຕິດຕໍ່",
    "Physical Address": "ທີ່ຢູ່",
    "Not provided": "ບໍ່ມີ",
    "No address registered": "ບໍ່ມີທີ່ຢູ່",
    "Express": "ບໍລິສັດຂົນສົ່ງ",
    "Close Profile": "ປິດໂປຣໄຟລ໌",
    "Add details to owner-imported product listings": "ເພີ່ມລາຍລະອຽດໃຫ້ກັບລາຍການສິນຄ້າທີ່ນຳເຂົ້າໂດຍເຈົ້າຂອງ",
    "No products found": "ບໍ່ພົບສິນຄ້າ",
    "Upload and manage active background banners on the landing page slider.": "ອັບໂຫລດ ແລະ ຈັດການແບນເນີພື້ນຫຼັງໃນໜ້າທຳອິດ.",
    "Upload New Banner": "ອັບໂຫລດແບນເນີໃໝ່",
    "Slideshow Settings": "ການຕັ້ງຄ່າສະໄລ້",
    "Set the transition speed of the background image carousel in seconds.": "ຕັ້ງເວລາການປ່ຽນຮູບພາບພື້ນຫຼังເປັນວິນາທີ.",
    "Slide Interval:": "ໄລຍະເວລາສະໄລ້:",
    "1 Second": "1 ວິນາທີ",
    "2 Seconds": "2 ວິນາທີ",
    "3 Seconds": "3 ວິນາທີ",
    "4 Seconds": "4 ວິນາທີ",
    "5 Seconds": "5 ວິນາທີ",
    "6 Seconds": "6 ວິນາທີ",
    "8 Seconds": "8 ວິນາທີ",
    "10 Seconds": "10 ວິນາທີ",
    "Loading banners...": "ກຳລັງໂຫລດແບນເນີ...",
    "No Custom Banners": "ບໍ່ມີແບນເນີແບບກຳນົດເອງ",
    "Create a beautiful homepage! Upload custom high-resolution banner photos to display in the main slideshow rotation.": "ສ້າງໜ້າທຳອິດທີ່ສວຍງາມ! ອັບໂຫລດຮູບພາບແບນເນີທີ່ມີຄວາມລະອຽດສູງເພື່ອສະແດງໃນສະໄລ້.",
    "Upload First Banner": "ອັບໂຫລດແບນເນີທຳອິດ",
    "Delete": "ລົບ",
    "Orders & Shipping": "ລາຍການສັ່ງຊື້ & ຈັດສົ່ງ",
    "Manage order statuses and shipping": "ຈັດການສະຖານະລາຍການສັ່ງຊື້ ແລະ ການຈັດສົ່ງ",
    "Order #": "ເລກທີໃບບິນ",
    "Date": "ວັນທີ",
    "Update Status": "ອັບເດດສະຖານະ",
    "All": "ທັງໝົດ",
    "Pending": "ລໍຖ້າການຊຳລະ",
    "Preparing": "ກຳລັງກຽມ",
    "Shipping": "ກຳລັງຈັດສົ່ງ",
    "Received": "ໄດ້ຮັບແລ້ວ",
    "Pending Payment": "ລໍຖ້າການຊຳລະເງິນ",
    "Prepare": "ກຳລັງກຽມ",
    "Sending": "ກຳລັງຈັດສົ່ງ",
    "No orders found": "ບໍ່ພົບລາຍການສັ່ງຊື້",
    "Total Revenue Report": "ລາຍງານລາຍຮັບທັງໝົດ",
    "Detailed breakdown of sales income and orders": "ລາຍລະອຽດລາຍຮັບຈາກການຂາຍ ແລະ ໃບບິນ",
    "Import Revenue Report": "ລາຍງານຕົ້ນທຶນນຳເຂົ້າ",
    "Detailed breakdown of product import costs": "ລາຍລະອຽດຕົ້ນທຶນການນຳເຂົ້າສິນຄ້າ",
    "Total Earned": "ລາຍຮັບທັງໝົດ",
    "Exclude pending": "ບໍ່ລວມລາຍການລໍຖ້າ",
    "Orders Completed": "ລາຍການສຳເລັດ",
    "Paid/received items": "ລາຍການຊຳລະແລ້ວ/ໄດ້ຮັບແລ້ວ",
    "Avg Order Value": "ມູນຄ່າສະເລ່ຍ",
    "Per paid transaction": "ຕໍ່ທຸລະກຳ",
    "Pending Income": "ລາຍຮັບລໍຖ້າ",
    "orders awaiting proof": "ລາຍການລໍຖ້າຫຼັກຖານ",
    "Analyzing sales history...": "ກຳລັງວິເຄາະປະຫວັດການຂາຍ...",
    "Customer Info": "ຂໍ້ມູນລູກຄ້າ",
    "Date Issued": "ວັນທີອອກ",
    "Revenue Amount": "ຍອດລາຍຮັບ",
    "No matching sales or orders found.": "ບໍ່ພົບລາຍການຂາຍ ຫຼື ໃບບິນ.",
    "Order Breakdown": "ລາຍລະອຽດໃບບິນ",
    "Customer Details": "ຂໍ້ມູນລູກຄ້າ",
    "Recipient Name": "ຊື່ຜູ້ຮັບ",
    "Order Date": "ວັນທີສັ່ງຊື້",
    "Order Time": "ເວລາສັ່ງຊື້",
    "Total Paid": "ຍອດຊຳລະ",
    "BCEL One QR Receipt": "ໃບຮັບ BCEL One QR",
    "Open Slip": "ເປີດສະລິບ",
    "Verify & Approve": "ຢືນຢັນ & ອະນຸມັດ",
    "Purchased Items": "ສິນຄ້າທີ່ຊື້",
    "All Statuses": "ທຸກສະຖານະ",
    "Awaiting Payment": "ລໍຖ້າການຊຳລະ",
    "Procurement Spent": "ຕົ້ນທຶນຈັດຊື້",
    "Total import cost value": "ມູນຄ່າການນຳເຂົ້າທັງໝົດ",
    "Total Qty Imported": "ຈຳນວນນຳເຂົ້າທັງໝົດ",
    "Total items in stock intake": "ຈຳນວນສິນຄ້ານຳເຂົ້າທັງໝົດ",
    "Avg Procurement Cost": "ຕົ້ນທຶນຈັດຊື້ສະເລ່ຍ",
    "Per import batch ticket": "ຕໍ່ລາຍການນຳເຂົ້າ",
    "Unique Items": "ສິນຄ້າບໍ່ຊ້ຳ",
    "Distinct products stocked": "ສິນຄ້າທີ່ແຕກຕ່າງກັນໃນຄັງ",
    "Fetching import records...": "ກຳລັງດຶງຂໍ້ມູນການນຳເຂົ້າ...",
    "Import ID": "ລະຫັດນຳເຂົ້າ",
    "Product Details": "ລາຍລະອຽດສິນຄ້າ",
    "Quantity": "ຈຳນວນ",
    "Unit Cost": "ລາຄາຕໍ່ໜ່ວຍ",
    "Total Expense": "ລວມຄ່າໃຊ້ຈ່າຍ",
    "No matching import records found.": "ບໍ່ພົບບັນທຶກການນຳເຂົ້າ.",
    "Search product or supplier...": "ຄົ້ນຫາສິນຄ້າ ຫຼື ຜູ້ສະໜອງ...",
    "Save Details": "ບັນທຶກລາຍລະອຽດ",
    "Cancel": "ຍົກເລີກ",
    "Saving...": "ກຳລັງບັນທຶກ...",
    "Description": "ລາຍລະອຽດ",
    "Ingredients": "ສ່ວນປະກອບ",
    "Welcome back, ": "ຍິນດີຕ້ອນຮັບກັບຄືນ, ",
    ". Here's your store overview.": ". ນີ້ແມ່ນພາບລວມຮ້ານຂອງທ່ານ.",
    "Total Orders": "ລາຍການສັ່ງຊື້ທັງໝົດ",
    "Recent Orders": "ລາຍການສັ່ງຊື້ຫຼ້າສຸດ",
    "View All": "ເບິ່ງທັງໝົດ",
    "Order": "ໃບບິນ",
    "No orders yet": "ຍັງບໍ່ມີລາຍການສັ່ງຊື້",
    "All stocked up ✓": "ສິນຄ້າມີພຽງພໍທັງໝົດ ✓",
    "Top Selling Products": "ສິນຄ້າຂາຍດີທີ່ສຸດ",
    "No sales yet": "ຍັງບໍ່ມີຍອດຂາຍ",
    "Quick Actions": "ດຳເນີນການດ່ວນ",
    "Manage Users": "ຈັດການຜູ້ໃຊ້",
    "Employee Portal": "ພອດທໍພະນັກງານ",
    "Loading analytics": "ກຳລັງໂຫລດການວິເຄາະ",
    "Employee Dashboard": "ກະດານຄວບຄຸມພະນັກງານ",
    "Welcome, ": "ຍິນດີຕ້ອນຮັບ, ",
    ". Here's today's overview.": ". ນີ້ແມ່ນພາບລວມຂອງມື້ນີ້.",
    "Pending Orders": "ລາຍການທີ່ລໍຖ້າ",
    "New Orders": "ລາຍການມາໃໝ່",
    "New": "ໃໝ່",
    "Employee Sales Log": "ບັນທຶກການຂາຍຂອງພະນັກງານ",
    "Orders Sold": "ລາຍການທີ່ຂາຍໄດ້",
    "No employee sales records found": "ບໍ່ພົບຂໍ້ມູນການຂາຍຂອງພະນັກງານ",
    "No orders sold yet": "ຍັງບໍ່ມີລາຍການຂາຍເທື່ອ",
    "Shipped Today": "ຈັດສົ່ງມື້ນີ້",
    "No recent orders": "ບໍ່ມີລາຍການສັ່ງຊື້ຫຼ້າສຸດ",
    "Manage Products": "ຈັດການສິນຄ້າ",
    "Manage Orders & Shipping": "ຈັດການລາຍການສັ່ງຊື້ & ຈັດສົ່ງ",
    "View Storefront": "ເບິ່ງໜ້າຮ້ານ",
    "Orders by Status": "ລາຍການສັ່ງຊື້ຕາມສະຖານະ",
    "Loading dashboard": "ກຳລັງໂຫລດກະດານຄວບຄຸມ"
  },
  th: {
    // Navbar
    home: 'หน้าแรก',
    shop: 'ร้านค้า',
    our_story: 'เรื่องราวของเรา',
    admin: 'ผู้ดูแล',
    portal: 'พอร์ทัลพนักงาน',
    my_account: 'บัญชีของฉัน',
    logout: 'ออกจากระบบ',
    sign_in: 'เข้าสู่ระบบ',
    cart: 'ตะกร้า',

    // Hero / landing
    hero_title: 'ธรรมชาติแท้ รังสรรค์ในลาว',
    hero_desc: 'สัมผัสการบำรุงจากธรรมชาติของหลวงพระบาง ผลิตภัณฑ์บำรุงผิวทำมือสำหรับกิจวัตรประจำวันของคุณ',
    hero_button: 'ช้อปคอลเลกชันนี้',
    popular_title: 'สินค้ายอดนิยม',
    popular_subtitle: 'ผลิตภัณฑ์บำรุงผิวจากธรรมชาติที่ได้รับความนิยมที่สุดในลาว',
    view_all: 'ดูทั้งหมด',
    story_title: 'เรื่องราวของเรา',
    story_subtitle: 'ตั้งแต่ปี 2011 Lao Natural ดำเนินงานภายใต้ 3 พันธกิจหลัก:',
    
    // Missions
    mission1_title: 'มอบผลิตภัณฑ์ลาวอย่างแท้จริง',
    mission1_desc: 'เราสร้างสรรค์ผลิตภัณฑ์ลาวที่แท้จริงโดยใช้วัตถุดิบท้องถิ่น เพื่อสนับสนุนชุมชนและมอบประสบการณ์ลาวอย่างแท้จริง',
    mission2_title: 'สนับสนุนกลุ่มชาติพันธุ์',
    mission2_desc: 'เราเสริมสร้างศักยภาพกลุ่มชาติพันธุ์โดยสร้างโอกาสการทำงานและสนับสนุนการศึกษา ช่วยพัฒนาคุณภาพชีวิตและการเติบโตของชุมชน',
    mission3_title: 'ส่งเสริมความรับผิดชอบต่อสิ่งแวดล้อม',
    mission3_desc: 'เราให้ความสำคัญกับความยั่งยืนผ่านบรรจุภัณฑ์ที่เป็นมิตรต่อสิ่งแวดล้อม ลดขยะ และจัดหาวัตถุดิบอย่างรับผิดชอบเพื่อลดผลกระทบต่อสิ่งแวดล้อม',

    // Ingredients
    ingredients_title: "ส่วนผสมหลักของเรา",
    ingredients_subtitle: 'พืชพรรณธรรมชาติที่บริสุทธิ์ที่สุดเพื่อบำรุงผิวและจิตวิญญาณของคุณ',
    ing_frangipani: 'ดอกลีลาวดี',
    ing_honey: 'น้ำผึ้งป่า',
    ing_lemongrass: 'ตะไคร้',
    ing_coconut: 'มะพร้าว',
    ing_rice: 'ข้าว',
    ing_coffee: 'กาแฟ',
    ing_peppermint: 'สะระแหน่',
    ing_turmeric: 'ขมิ้นชัน',

    // Footer
    footer_desc: 'ผลิตภัณฑ์บำรุงผิวและสุขภาพทำมือจากธรรมชาติส่งตรงจากหลวงพระบาง มอบสัมผัสแห่งการเยียวยาจากธรรมชาติในทุกวันของคุณ',
    quick_links: 'ลิงก์ด่วน',
    contact: 'ติดต่อเรา',
    scan_qr: 'สแกน QR',
    scan_desc: 'สแกนเพื่อเข้าชมเพจทางการของเราหรือเสร็จสิ้นการโอนเงินชำระค่าสินค้า',
    rights_reserved: 'Lao Natural Essentials. สงวนลิขสิทธิ์ทั้งหมด.',

    // Products page
    products_title: 'ผลิตภัณฑ์ทั้งหมด',
    products_subtitle: 'สกินแคร์ออร์แกนิกและตำรับทำมือจากหลวงพระบาง',
    all_categories: 'หมวดหมู่ทั้งหมด',
    search_placeholder: 'ค้นหาผลิตภัณฑ์...',
    sort_by: 'จัดเรียงตาม',
    sort_featured: 'แนะนำ',
    sort_low_high: 'ราคา: ต่ำไปสูง',
    sort_high_low: 'ราคา: สูงไปต่ำ',
    sort_in_stock: 'มีในสต็อก',
    view_details: 'ดูรายละเอียด',

    // Product Detail page
    back_products: 'กลับไปหน้าสินค้า',
    select_size: 'เลือกขนาด',
    quantity: 'จำนวน',
    add_to_cart: 'เพิ่มลงตะกร้า',
    out_of_stock: 'สินค้าหมด',
    ingredients_tab: 'ส่วนผสม',
    description_tab: 'รายละเอียด',
    size_price: 'ขนาดและราคา',

    // Cart page
    cart_title: 'ตะกร้าของคุณ',
    cart_empty: 'ไม่มีสินค้าในตะกร้าของคุณ',
    continue_shopping: 'เลือกซื้อสินค้าต่อ',
    item: 'สินค้า',
    price: 'ราคา',
    qty: 'จำนวน',
    total: 'รวม',
    subtotal: 'ยอดรวมย่อย',
    proceed_checkout: 'ดำเนินการชำระเงิน',

    // Checkout page
    checkout_title: 'ชำระเงิน',
    contact_info: 'ข้อมูลติดต่อ',
    shipping_details: 'รายละเอียดการจัดส่ง',
    full_name: 'ชื่อ-นามสกุล',
    phone_number: 'เบอร์โทรศัพท์',
    country: 'ประเทศ',
    province: 'แขวง/จังหวัด',
    delivery_address: 'ที่อยู่สำหรับจัดส่ง',
    express_company: 'บริษัทขนส่งด่วน',
    express_placeholder: 'เช่น HAL Express, Anousith เป็นต้น',
    order_summary: 'สรุปการสั่งซื้อ',
    place_order: 'สั่งซื้อสินค้าและชำระเงิน',
    shipping_cost: 'ค่าจัดส่ง',
    coupon_code: 'รหัสคูปอง',
    apply: 'ใช้',

    // Order Detail page
    order_tracking: 'ติดตามคำสั่งซื้อ',
    status: 'สถานะ',
    tracking_number: 'หมายเลขติดตามพัสดุ',
    delivery_info: 'ข้อมูลการจัดส่ง',
    submit_proof: 'แนบหลักฐานการชำระเงิน',
    proof_desc: 'อัปโหลดสลิปการโอนเงินเพื่อดำเนินการสั่งซื้อให้เสร็จสิ้น',
    choose_file: 'เลือกไฟล์',
    upload_slip: 'อัปโหลดสลิป',
    status_pending: 'รอตรวจสอบการชำระเงิน',
    status_prepare: 'กำลังเตรียมสินค้า',
    status_sending: 'จัดส่งแล้วระหว่างทาง',
    status_received: 'ได้รับสินค้าแล้ว',

    // Dashboard
    profile_details: 'รายละเอียดโปรไฟล์',
    order_history: 'ประวัติคำสั่งซื้อ',
    no_orders: 'คุณยังไม่มีประวัติการสั่งซื้อ',

    // Login
    email_address: 'ที่อยู่อีเมล',
    dont_have_account: 'ยังไม่มีบัญชีใช่หรือไม่? สมัครสมาชิกที่นี่',

    // Portal additions
    "Dashboard": "แดชบอร์ด",
    "Total Revenue": "รายได้ทั้งหมด",
    "Import Revenue": "ต้นทุนนำเข้า",
    "Sell History": "ประวัติการขาย",
    "Reports & Invoices": "รายงาน & ใบเสร็จ",
    "Import Products": "นำเข้าสินค้า",
    "Product Catalog": "รายการสินค้า",
    "Category Management": "จัดการหมวดหมู่",
    "All Users": "ผู้ใช้ทั้งหมด",
    "Employees": "พนักงาน",
    "Customers": "ลูกค้า",
    "View Store": "ดูหน้าร้าน",
    "Sign Out": "ออกจากระบบ",
    "Hero Banners": "แบนเนอร์โฆษณา",
    "Products": "สินค้า",
    "Categories": "หมวดหมู่",
    "Orders": "รายการสั่งซื้อ",
    "Add products to the store catalog": "เพิ่มรายละเอียดในรายการสินค้าที่นำเข้าโดยเจ้าของ",
    "Import Product": "นำเข้าสินค้า",
    "Total Products": "สินค้าทั้งหมด",
    "Low Stock": "สินค้าใกล้หมด",
    "Out of Stock": "สินค้าหมด",
    "Product": "สินค้า",
    "Category": "หมวดหมู่",
    "Price": "ราคา",
    "Stock": "คลังสินค้า",
    "Actions": "การจัดการ",
    "No products imported yet": "ยังไม่มีสินค้านำเข้า",
    "Edit Product": "แก้ไขสินค้า",
    "Import New Product": "นำเข้าสินค้าใหม่",
    "Product Image": "รูปภาพสินค้า",
    "Product Name *": "ชื่อสินค้า *",
    "Supplier Name (Optional)": "ชื่อผู้จัดส่ง/ซัพพลายเออร์ (ถ้ามี)",
    "Import Date": "วันที่นำเข้า",
    "Import Price (₭) *": "ราคานำเข้า (₭) *",
    "Sell Price (₭) *": "ราคาขาย (₭) *",
    "Stock *": "คลังสินค้า *",
    "Import History": "ประวัติการนำเข้า",
    "Supplier": "ผู้จัดส่ง",
    "Import Price": "ราคานำเข้า",
    "Imported Qty": "จำนวนนำเข้า",
    "No imports recorded for this product": "ไม่มีบันทึกการนำเข้าสำหรับสินค้านี้",
    "Detailed inventory and product information": "ข้อมูลสินค้าและคลังสินค้าอย่างละเอียด",
    "Search by name, ID, or category...": "ค้นหาด้วยชื่อ รหัส หรือหมวดหมู่...",
    "Loading botanicals...": "กำลังโหลดข้อมูลสมุนไพร...",
    "units": "ชิ้น",
    "No products found in the catalog": "ไม่พบสินค้าในรายการ",
    "Uncategorized": "ไม่มีหมวดหมู่",
    "Sell Price": "ราคาขาย",
    "In Stock": "มีในคลัง",
    "Imported By": "นำเข้าโดย",
    "Verified": "ยืนยันแล้ว",
    "No description available for this botanical product.": "ไม่มีรายละเอียดสำหรับสินค้านี้",
    "Ingredients not specified.": "ไม่ได้ระบุส่วนประกอบ",
    "Unit Size": "ขนาดบรรจุ",
    "Close Catalog": "ปิดหน้ารายการ",
    "Manage product categories for the store": "จัดการหมวดหมู่สินค้าสำหรับร้านค้า",
    "Search categories...": "ค้นหาหมวดหมู่...",
    "No categories found.": "ไม่พบหมวดหมู่",
    "New Category": "หมวดหมู่ใหม่",
    "Edit Category": "แก้ไขหมวดหมู่",
    "Save Category": "บันทึกหมวดหมู่",
    "Category Name": "ชื่อหมวดหมู่",
    "View and manage all customer transactions": "ดูและจัดการรายการธุรกรรมของลูกค้าทั้งหมด",
    "Search orders...": "ค้นหารากการสั่งซื้อ...",
    "Fetching records...": "กำลังดึงข้อมูล...",
    "Order ID": "รหัสใบสั่งซื้อ",
    "Customer": "ลูกค้า",
    "Date & Time": "วันที่ & เวลา",
    "Total Amount": "ยอดรวมทั้งหมด",
    "No orders found matching your search.": "ไม่พบรายการสั่งซื้อที่ค้นหา",
    "Order Details": "รายละเอียดใบสั่งซื้อ",
    "Order Summary": "สรุปรายการสั่งซื้อ",
    "Subtotal": "ยอดรวม",
    "Payment Slip": "สลิปการจ่ายเงิน",
    "Shipping Address": "ที่อยู่จัดส่ง",
    "No screenshot slip uploaded yet.": "ยังไม่ได้อัปโหลดสลิปการโอนเงิน",
    "Verify Payment & Prepare Order": "ยืนยันการชำระเงิน & เตรียมสินค้า",
    "Ship Order (Add Tracking Number)": "จัดส่งสินค้า (ใส่เลขติดตามพัสดุ)",
    "Complete / Set Received": "เสร็จสมบูรณ์ / ตั้งค่าเป็นได้รับแล้ว",
    "Mark Order as Received": "ทำเครื่องหมายว่าได้รับสินค้าแล้ว",
    "Close Details": "ปิดหน้ารายละเอียด",
    "Generate and print authentic Lao Natural Sole Co. invoices and track transactions": "สร้างและพิมพ์ใบเสร็จบริษัท ลาว เนเชอรัล และติดตามรายการธุรกรรม",
    "All Time": "ทั้งหมด",
    "Today": "วันนี้",
    "Past 7 Days": "7 วันที่ผ่านมา",
    "Past 30 Days": "30 วันที่ผ่านมา",
    "Search invoices...": "ค้นหาใบเสร็จ...",
    "Total Sales": "ยอดขายทั้งหมด",
    "Total Revenue (LAK)": "รายได้ทั้งหมด (กีบ)",
    "Shipping Collected": "ค่าจัดส่งที่เก็บได้",
    "Items Sold": "จำนวนสินค้าที่ขายได้",
    "Invoices List": "รายการใบเสร็จ",
    "Total": "ยอดรวม",
    "Print Invoice": "พิมพ์ใบเสร็จ",
    "Lao Natural Sole Co., Ltd": "บริษัท ลาว เนเชอรัล จำกัด",
    "Ban Mano, Luang Prabang, Laos": "บ้าน มโน, หลวงพระบาง, ลาว",
    "INVOICE": "INVOICE",
    "Invoice To:": "ส่งถึง:",
    "Invoice Details:": "รายละเอียดใบเสร็จ:",
    "Invoice No:": "เลขที่ใบเสร็จ:",
    "Date:": "วันที่:",
    "Payment Method:": "วิธีการชำระเงิน:",
    "BCEL One Transfer": "โอนผ่าน BCEL One",
    "Item Description": "รายการสินค้า",
    "Qty": "จำนวน",
    "Unit Price": "ราคาต่อหน่วย",
    "Amount": "มูลค่า",
    "VAT (10%)": "ภาษีมูลค่าเพิ่ม (10%)",
    "Shipping Cost": "ค่าจัดส่ง",
    "Grand Total": "ยอดรวมสุทธิ",
    "Thank you for your business!": "ขอบคุณที่ใช้บริการ!",
    "Authorized Signature": "ลายมือชื่อผู้มีอำนับ",
    "Manage store employees": "จัดการพนักงานร้าน",
    "View registered customers": "ดูรายชื่อลูกค้าที่ลงทะเบียน",
    "All employees & customers": "พนักงาน & ลูกค้าทั้งหมด",
    "Search users...": "ค้นหาผู้ใช้งาน...",
    "Add Employee": "เพิ่มพนักงาน",
    "Add Customer": "เพิ่มลูกค้า",
    "Add User": "เพิ่มผู้ใช้",
    "User Details": "รายละเอียดผู้ใช้งาน",
    "Joined": "เข้าร่วมเมื่อ",
    "No phone": "ไม่มีเบอร์โทร",
    "No users found": "ไม่พบผู้ใช้",
    "Add New User": "เพิ่มผู้ใช้งานใหม่",
    "Edit User": "แก้ไขผู้ใช้งาน",
    "Profile Picture (Optional)": "รูปโปรไฟล์ (ถ้ามี)",
    "Full Name *": "ชื่อเต็ม *",
    "Email *": "อีเมล *",
    "Password *": "รหัสผ่าน *",
    "Password (leave blank to keep)": "รหัสผ่าน (เว้นว่างไว้หากไม่ต้องการเปลี่ยน)",
    "Phone": "เบอร์โทรศัพท์",
    "Address": "ที่อยู่",
    "Create User": "สร้างผู้ใช้งาน",
    "Save Changes": "บันทึกการเปลี่ยนแปลง",
    "User Profile": "โปรไฟล์ผู้ใช้งาน",
    "Email Address": "ที่อยู่อีเมล",
    "Contact Number": "เบอร์โทรศัพท์ติดต่อ",
    "Physical Address": "ที่อยู่",
    "Not provided": "ไม่มี",
    "No address registered": "ไม่มีที่อยู่",
    "Express": "บริษัทขนส่ง",
    "Close Profile": "ปิดโปรไฟล์",
    "Add details to owner-imported product listings": "เพิ่มรายละเอียดในรายการสินค้าที่นำเข้าโดยเจ้าของ",
    "No products found": "ไม่พบสินค้า",
    "Upload and manage active background banners on the landing page slider.": "อัปโหลดและจัดการแบนเนอร์พื้นหลังในหน้าแรก",
    "Upload New Banner": "อัปโหลดแบนเนอร์ใหม่",
    "Slideshow Settings": "การตั้งค่าสไลด์โชว์",
    "Set the transition speed of the background image carousel in seconds.": "ตั้งเวลาการเปลี่ยนรูปภาพพื้นหลังเป็นวินาที",
    "Slide Interval:": "เวลาในการสไลด์:",
    "1 Second": "1 วินาที",
    "2 Seconds": "2 วินาที",
    "3 Seconds": "3 วินาที",
    "4 Seconds": "4 วินาที",
    "5 Seconds": "5 วินาที",
    "6 Seconds": "6 วินาที",
    "8 Seconds": "8 วินาที",
    "10 Seconds": "10 วินาที",
    "Loading banners...": "กำลังโหลดแบนเนอร์...",
    "No Custom Banners": "ไม่มีแบนเนอร์ที่กำหนดเอง",
    "Create a beautiful homepage! Upload custom high-resolution banner photos to display in the main slideshow rotation.": "สร้างหน้าแรกที่สวยงาม! อัปโหลดรูปภาพแบนเนอร์ที่มีความละเอียดสูงเพื่อแสดงในสไลด์โชว์หลัก",
    "Upload First Banner": "อัปโหลดแบนเนอร์แรก",
    "Delete": "ลบ",
    "Orders & Shipping": "รายการสั่งซื้อ & จัดส่ง",
    "Manage order statuses and shipping": "จัดการสถานะรายการสั่งซื้อและการจัดส่ง",
    "Order #": "เลขที่ใบสั่งซื้อ",
    "Date": "วันที่",
    "Update Status": "อัปเดตสถานะ",
    "All": "ทั้งหมด",
    "Pending": "รอชำระเงิน",
    "Preparing": "กำลังเตรียมสินค้า",
    "Shipping": "กำลังจัดส่ง",
    "Received": "ได้รับแล้ว",
    "Pending Payment": "รอชำระเงิน",
    "Prepare": "กำลังเตรียมสินค้า",
    "Sending": "กำลังจัดส่ง",
    "No orders found": "ไม่พบรายการสั่งซื้อ",
    "Total Revenue Report": "รายงานรายได้ทั้งหมด",
    "Detailed breakdown of sales income and orders": "รายละเอียดรายได้จากการขายและใบสั่งซื้อ",
    "Import Revenue Report": "รายงานต้นทุนนำเข้า",
    "Detailed breakdown of product import costs": "รายละเอียดต้นทุนการนำเข้าสินค้า",
    "Total Earned": "รายได้ทั้งหมด",
    "Exclude pending": "ไม่รวมรายการรอ",
    "Orders Completed": "รายการสำเร็จ",
    "Paid/received items": "รายการชำระแล้ว/ได้รับแล้ว",
    "Avg Order Value": "มูลค่าเฉลี่ย",
    "Per paid transaction": "ต่อรายการ",
    "Pending Income": "รายได้รอ",
    "orders awaiting proof": "รายการรอหลักฐาน",
    "Analyzing sales history...": "กำลังวิเคราะห์ประวัติการขาย...",
    "Customer Info": "ข้อมูลลูกค้า",
    "Date Issued": "วันที่ออก",
    "Revenue Amount": "ยอดรายได้",
    "No matching sales or orders found.": "ไม่พบรายการขายหรือใบสั่งซื้อ",
    "Order Breakdown": "รายละเอียดใบสั่งซื้อ",
    "Customer Details": "ข้อมูลลูกค้า",
    "Recipient Name": "ชื่อผู้รับ",
    "Order Date": "วันที่สั่งซื้อ",
    "Order Time": "เวลาสั่งซื้อ",
    "Total Paid": "ยอดชำระ",
    "BCEL One QR Receipt": "ใบเสร็จ BCEL One QR",
    "Open Slip": "เปิดสลิป",
    "Verify & Approve": "ยืนยัน & อนุมัติ",
    "Purchased Items": "สินค้าที่ซื้อ",
    "All Statuses": "สถานะทั้งหมด",
    "Awaiting Payment": "รอชำระเงิน",
    "Procurement Spent": "ต้นทุนจัดซื้อ",
    "Total import cost value": "มูลค่าการนำเข้าทั้งหมด",
    "Total Qty Imported": "จำนวนนำเข้าทั้งหมด",
    "Total items in stock intake": "จำนวนสินค้านำเข้าทั้งหมด",
    "Avg Procurement Cost": "ต้นทุนจัดซื้อเฉลี่ย",
    "Per import batch ticket": "ต่อรายการนำเข้า",
    "Unique Items": "สินค้าไม่ซ้ำ",
    "Distinct products stocked": "สินค้าที่แตกต่างกันในคลัง",
    "Fetching import records...": "กำลังดึงข้อมูลการนำเข้า...",
    "Import ID": "รหัสนำเข้า",
    "Product Details": "รายละเอียดสินค้า",
    "Quantity": "จำนวน",
    "Unit Cost": "ราคาต่อหน่วย",
    "Total Expense": "ค่าใช้จ่ายรวม",
    "No matching import records found.": "ไม่พบบันทึกการนำเข้า",
    "Search product or supplier...": "ค้นหาสินค้าหรือซัพพลายเออร์...",
    "Save Details": "บันทึกรายละเอียด",
    "Cancel": "ยกเลิก",
    "Saving...": "กำลังบันทึก...",
    "Description": "รายละเอียด",
    "Ingredients": "ส่วนประกอบ",
    "Welcome back, ": "ยินดีต้อนรับกลับ, ",
    ". Here's your store overview.": ". นี่คือภาพรวมร้านค้าของคุณ",
    "Total Orders": "รายการสั่งซื้อทั้งหมด",
    "Recent Orders": "รายการสั่งซื้อล่าสุด",
    "View All": "ดูทั้งหมด",
    "Order": "ใบเสร็จ",
    "No orders yet": "ยังไม่มีรายการสั่งซื้อ",
    "All stocked up ✓": "สินค้ามีเพียงพอทั้งหมด ✓",
    "Top Selling Products": "สินค้าขายดีที่สุด",
    "No sales yet": "ยังไม่มียอดขาย",
    "Quick Actions": "ดำเนินการด่วน",
    "Manage Users": "จัดการผู้ใช้งาน",
    "Employee Portal": "พอร์ทัลพนักงาน",
    "Loading analytics": "กำลังโหลดการวิเคราะห์",
    "Employee Dashboard": "แดชบอร์ดพนักงาน",
    "Welcome, ": "ยินดีต้อนรับ, ",
    ". Here's today's overview.": ". นี่คือภาพรวมของวันนี้",
    "Pending Orders": "รายการที่รอ",
    "New Orders": "รายการมาใหม่",
    "New": "ใหม่",
    "Employee Sales Log": "บันทึกการขายของพนักงาน",
    "Orders Sold": "รายการที่ขายได้",
    "No employee sales records found": "ไม่พบข้อมูลการขายของพนักงาน",
    "No orders sold yet": "ยังไม่มีรายการขาย",
    "Shipped Today": "จัดส่งวันนี้",
    "No recent orders": "ไม่มีรายการสั่งซื้อล่าสุด",
    "Manage Products": "จัดการสินค้า",
    "Manage Orders & Shipping": "จัดการรายการสั่งซื้อ & จัดส่ง",
    "View Storefront": "ดูหน้าร้าน",
    "Orders by Status": "รายการสั่งซื้อตามสถานะ",
    "Loading dashboard": "กำลังโหลดแดชบอร์ด"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (key) => {
    if (translations[language] && translations[language][key] !== undefined) {
      return translations[language][key];
    }
    // Fallback to English
    if (translations.en && translations.en[key] !== undefined) {
      return translations.en[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
